// ─── Gallery.tsx — Masonry photo gallery with lightbox ───────────────────────
import { useState, useEffect, useCallback } from 'react'
import { useNavigate } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import { ChevronLeft, ChevronRight, X, Expand } from 'lucide-react'
import Modal from '../components/ui/Modal'
import Badge from '../components/ui/Badge'
import Button from '../components/ui/Button'
import { getStorageItem } from '../utils/storage'
import { STORAGE_KEYS } from '../utils/constants'
import type { GalleryPhoto } from '../types'

// ── Category config ───────────────────────────────────────────────────────────
type Category = 'all' | 'selfies' | 'wedding' | 'trips' | 'funny' | 'family' | 'special'

const CATEGORIES: { key: Category; label: string; emoji: string }[] = [
  { key: 'all',     label: 'All',     emoji: '🌸' },
  { key: 'selfies', label: 'Selfies', emoji: '🤳' },
  { key: 'wedding', label: 'Wedding', emoji: '💍' },
  { key: 'trips',   label: 'Trips',   emoji: '✈️' },
  { key: 'funny',   label: 'Funny',   emoji: '😂' },
  { key: 'family',  label: 'Family',  emoji: '👨‍👩‍👧' },
  { key: 'special', label: 'Special', emoji: '⭐' },
]

// ── Placeholder photos (used when no admin-uploaded photos exist) ──────────────
const PLACEHOLDER_PHOTOS: GalleryPhoto[] = [
  { id: 'g1', src: '/images/placeholder/gallery-1.jpg', alt: 'Our first selfie together', category: 'selfies',  date: 'October 2019' },
  { id: 'g2', src: '/images/placeholder/gallery-2.jpg', alt: 'Wedding ceremony',         category: 'wedding',  date: 'Our Wedding Day' },
  { id: 'g3', src: '/images/placeholder/gallery-3.jpg', alt: 'Trip to the mountains',    category: 'trips',    date: '2022' },
  { id: 'g4', src: '/images/placeholder/gallery-4.jpg', alt: 'That ridiculous moment',   category: 'funny',    date: 'Every day' },
  { id: 'g5', src: '/images/placeholder/gallery-5.jpg', alt: 'Family gathering',         category: 'family',   date: '2021' },
  { id: 'g6', src: '/images/placeholder/gallery-6.jpg', alt: 'Our anniversary dinner',   category: 'special',  date: '2023' },
  { id: 'g7', src: '/images/placeholder/gallery-7.jpg', alt: 'Candid moment',            category: 'selfies',  date: '2024' },
  { id: 'g8',  src: '/images/placeholder/gallery-8.jpg',  alt: 'A cozy night out under the lights',       category: 'special', date: 'October 2022' },
  { id: 'g9',  src: '/images/placeholder/gallery-9.jpg',  alt: 'Lost in the monsoon mist together',       category: 'trips',   date: 'October 2022' },
  { id: 'g10', src: '/images/placeholder/gallery-10.jpg', alt: 'Just us and a lazy afternoon',            category: 'special', date: 'October 2022' },
  { id: 'g11', src: '/images/placeholder/gallery-11.jpg', alt: 'Chasing clouds on a hill trek',           category: 'trips',   date: 'October 2022' },
  { id: 'g12', src: '/images/placeholder/gallery-12.jpg', alt: 'A night out with the people we love',    category: 'family',  date: 'June 2023' },
  { id: 'g13', src: '/images/placeholder/gallery-13.jpg', alt: 'Date night, dressed up and glowing',      category: 'special', date: 'June 2023' },
  { id: 'g14', src: '/images/placeholder/gallery-14.jpg', alt: 'Rainy days in the hills, dancing in the drizzle', category: 'trips', date: 'July 2023' },
  { id: 'g15', src: '/images/placeholder/gallery-15.jpg', alt: 'A quiet ritual, a warm tradition',        category: 'family',  date: 'September 2023' },
  { id: 'g16', src: '/images/placeholder/gallery-16.jpg', alt: 'Picking wildflowers, holding hands',      category: 'special', date: 'November 2023' },
  { id: 'g17', src: '/images/placeholder/gallery-17.jpg', alt: 'Radiant in gold and orange',              category: 'special', date: 'April 2024' },
]

// ── Helper: load photos ───────────────────────────────────────────────────────
function loadPhotos(): GalleryPhoto[] {
  const stored = getStorageItem<GalleryPhoto[]>(STORAGE_KEYS.GALLERY)
  if (Array.isArray(stored) && stored.length > 0) return stored
  // Try to load any auto-imported gallery entries generated by scripts/import-images.js
  try {
    // Vite-friendly: attempt to eagerly load an optional generated file
    // (the file is generated by `scripts/import-images.js` into src/data/gallery_imported.ts)
    // import.meta.globEager returns an object mapping paths to modules if they exist.
    // eslint-disable-next-line no-undef
    const mods = import.meta.globEager('../data/gallery_imported.ts') as Record<string, any>
    const key = Object.keys(mods)[0]
    const imported = key ? mods[key].importedGallery : undefined
    if (Array.isArray(imported) && imported.length > 0) return [...imported]
  } catch (err) {
    // ignore — file not present or import not supported in this environment
  }
  return PLACEHOLDER_PHOTOS
}

// ── Lightbox ──────────────────────────────────────────────────────────────────
interface LightboxProps {
  photos: GalleryPhoto[]
  currentIndex: number
  onClose: () => void
  onPrev: () => void
  onNext: () => void
}

function Lightbox({ photos, currentIndex, onClose, onPrev, onNext }: LightboxProps) {
  const photo = photos[currentIndex]

  // Keyboard navigation (left/right/escape)
  useEffect(() => {
    function handleKey(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose()
      if (e.key === 'ArrowLeft') onPrev()
      if (e.key === 'ArrowRight') onNext()
    }
    document.addEventListener('keydown', handleKey)
    return () => document.removeEventListener('keydown', handleKey)
  }, [onClose, onPrev, onNext])

  if (!photo) return null

  return (
    <Modal
      isOpen={true}
      onClose={onClose}
      title={photo.alt}
      // allow full-width on small screens, larger on md+ via responsive classes
      contentClassName="max-w-full sm:max-w-4xl"
      describedBy={`lightbox-caption-${photo.id}`}
    >
      <div className="relative w-full flex flex-col items-center gap-4" onClick={(e) => e.stopPropagation()}>
        {/* Prev */}
        {photos.length > 1 && (
          <button
            onClick={(e) => { e.stopPropagation(); onPrev() }}
            aria-label="Previous photo"
            className="absolute left-4 top-1/2 -translate-y-1/2 z-10 w-11 h-11 flex items-center justify-center rounded-full bg-white/10 hover:bg-white/20 text-[#5a4040] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#B76E79]"
          >
            <ChevronLeft size={24} aria-hidden="true" />
          </button>
        )}

        {/* Photo or video */}
        <div className="w-full flex items-center justify-center">
          {/\.(mp4|mov|webm)$/i.test(photo.src) ? (
            <video
              controls
              autoPlay
              playsInline
              className="max-h-[70vh] max-w-full rounded-2xl shadow-2xl bg-black"
              aria-label={photo.alt}
            >
              <source src={photo.src} />
              Your browser does not support the video tag.
            </video>
          ) : (
            <img
              src={photo.src}
              alt={photo.alt}
              className="max-h-[70vh] max-w-full rounded-2xl object-contain shadow-2xl"
              onError={(e) => { const img = e.currentTarget; img.style.display = 'none' }}
            />
          )}
        </div>

        {/* Caption */}
        <div id={`lightbox-caption-${photo.id}`} className="text-center">
          <p className="text-[#5a4040] text-base font-medium">{photo.alt}</p>
          {photo.date && (
            <p className="text-[#5a4040]/60 text-sm mt-1">{photo.date}</p>
          )}
          <p className="text-[#5a4040]/40 text-xs mt-2">
            {currentIndex + 1} / {photos.length}
          </p>
        </div>

        {/* Next */}
        {photos.length > 1 && (
          <button
            onClick={(e) => { e.stopPropagation(); onNext() }}
            aria-label="Next photo"
            className="absolute right-4 top-1/2 -translate-y-1/2 z-10 w-11 h-11 flex items-center justify-center rounded-full bg-white/10 hover:bg-white/20 text-[#5a4040] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#B76E79]"
          >
            <ChevronRight size={24} aria-hidden="true" />
          </button>
        )}
      </div>
    </Modal>
  )
}

// ── Photo skeleton placeholder shown while image loads ────────────────────────
function PhotoSkeleton({ message }: { message?: string }) {
  return (
    <div
      className="w-full rounded-2xl overflow-hidden flex flex-col items-center justify-center min-h-[160px] sm:min-h-[192px] md:min-h-[224px]"
      style={{ background: 'linear-gradient(135deg, #FFD6E050 0%, #E8D5F550 100%)' }}
    >
      <div
        className="w-full h-28 sm:h-32"
        aria-hidden="true"
        style={{
          background: 'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.5) 50%, transparent 100%)',
          backgroundSize: '200% 100%',
          animation: 'shimmer 1.5s infinite',
        }}
      />

      <div className="p-3 text-center">
        <p role="status" aria-live="polite" className="text-sm text-[#B76E79]">
          {message ?? 'Hold on — a memory is loading ❤️'}
        </p>
      </div>
    </div>
  )
}

// ── Gallery ───────────────────────────────────────────────────────────────────
export default function Gallery() {
  const navigate = useNavigate()
  const allPhotos = loadPhotos()

  const [loadedIds, setLoadedIds] = useState<Set<string>>(new Set())
  const [selectedCategory, setSelectedCategory] = useState<Category>('all')
  const [lightboxIndex, setLightboxIndex] = useState<number | null>(null)

  const filteredPhotos =
    selectedCategory === 'all'
      ? allPhotos
      : allPhotos.filter((p) => p.category === selectedCategory)

  const openLightbox = useCallback((index: number) => {
    setLightboxIndex(index)
  }, [])

  const closeLightbox = useCallback(() => setLightboxIndex(null), [])

  const goPrev = useCallback(() => {
    setLightboxIndex((i) =>
      i === null ? null : (i - 1 + filteredPhotos.length) % filteredPhotos.length,
    )
  }, [filteredPhotos.length])

  const goNext = useCallback(() => {
    setLightboxIndex((i) =>
      i === null ? null : (i + 1) % filteredPhotos.length,
    )
  }, [filteredPhotos.length])

  return (
    <div
      className="min-h-screen px-4 py-16"
      style={{
        background:
          'linear-gradient(180deg, #F5ECD7 0%, rgba(255,214,224,0.2) 50%, #F5ECD7 100%)',
      }}
    >
      {/* ── Header ──────────────────────────────────────────────────────── */}
      <motion.header
        initial={{ opacity: 0, y: -24 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="text-center mb-10 max-w-2xl mx-auto"
        aria-label="Gallery section header"
      >
        <p className="text-[#B76E79]/80 text-sm font-medium uppercase tracking-widest mb-3">
          Chapter Two
        </p>
        <h1
          style={{ fontFamily: "'Playfair Display', serif" }}
          className="text-4xl sm:text-5xl font-bold text-[#B76E79] mb-4 drop-shadow-sm"
        >
          Our Memories
        </h1>
        <p className="text-[#5a4040]/65 text-base leading-relaxed">
          A thousand pictures, each one a moment I never want to forget.
        </p>
        <div className="flex items-center gap-3 mt-6 justify-center">
          <div className="h-px w-16 bg-[#B76E79]/30" />
          <span className="text-[#B76E79] text-lg" aria-hidden="true">📸</span>
          <div className="h-px w-16 bg-[#B76E79]/30" />
        </div>
      </motion.header>

      {/* ── Category filter ──────────────────────────────────────────────── */}
      <motion.nav
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.15 }}
        className="flex flex-wrap justify-center gap-2 mb-10 max-w-3xl mx-auto"
        aria-label="Filter photos by category"
      >
        {CATEGORIES.map((cat) => {
          const isActive = selectedCategory === cat.key
          return (
            <button
              key={cat.key}
              onClick={() => setSelectedCategory(cat.key)}
              aria-pressed={isActive}
              aria-label={`Filter by ${cat.label}`}
              className={[
                'inline-flex items-center gap-1.5 px-4 py-2 rounded-full text-sm font-medium',
                'transition-all duration-200 cursor-pointer',
                'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#B76E79]',
                isActive
                  ? 'text-white shadow-[0_2px_12px_rgba(183,110,121,0.35)]'
                  : 'bg-white/50 text-[#B76E79] border border-[#B76E79]/25 hover:bg-[#FFD6E0]/60',
              ].join(' ')}
              style={isActive ? { background: 'linear-gradient(135deg, #B76E79 0%, #c9828c 100%)' } : undefined}
            >
              <span aria-hidden="true">{cat.emoji}</span>
              {cat.label}
              {cat.key !== 'all' && (
                <span className={['text-xs', isActive ? 'text-white/70' : 'text-[#B76E79]/50'].join(' ')}>
                  ({allPhotos.filter((p) => p.category === cat.key).length})
                </span>
              )}
            </button>
          )
        })}
      </motion.nav>

      {/* ── Masonry grid ────────────────────────────────────────────────── */}
      {filteredPhotos.length === 0 ? (
        <div className="text-center py-20 text-[#B76E79]/50">
          <p className="text-5xl mb-4" aria-hidden="true">📷</p>
          <p className="text-lg">No photos in this category yet.</p>
          <p className="text-sm mt-1">Add some from the Admin Panel.</p>
        </div>
      ) : (
        <motion.div
          layout
          className="columns-2 sm:columns-2 md:columns-3 lg:columns-4 gap-4 max-w-7xl mx-auto"
          aria-label={`Photo gallery — ${filteredPhotos.length} photos`}
        >
          <AnimatePresence>
            {filteredPhotos.map((photo, idx) => (
              <motion.figure
                key={photo.id}
                layout
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.85 }}
                transition={{ duration: 0.35, delay: (idx % 8) * 0.05 }}
                className="break-inside-avoid mb-4 relative group rounded-2xl overflow-hidden cursor-pointer"
                onClick={() => openLightbox(idx)}
                tabIndex={0}
                role="button"
                aria-label={`View photo: ${photo.alt}`}
                onKeyDown={(e) => e.key === 'Enter' && openLightbox(idx)}
              >
                <div className="transition-transform duration-300 group-hover:scale-[1.03] relative">
                  {/\.(mp4|mov|webm)$/i.test(photo.src) ? (
                    <div className="w-full h-40 sm:h-48 md:h-56 rounded-2xl overflow-hidden bg-black relative">
                      <video
                        muted
                        playsInline
                        loop
                        preload="metadata"
                        className="w-full h-full object-cover block"
                        onLoadedData={() => setLoadedIds((prev) => new Set(prev).add(photo.id))}
                        onError={(e) => {
                          setLoadedIds((prev) => new Set(prev).add(photo.id))
                        }}
                      >
                        <source src={photo.src} />
                      </video>
                      <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                        <div className="w-10 h-10 rounded-full bg-black/40 flex items-center justify-center text-white text-xl">▶</div>
                      </div>
                    </div>
                  ) : (
                    <img
                      src={photo.src}
                      alt={photo.alt}
                      loading="lazy"
                      decoding="async"
                      className="w-full h-40 sm:h-48 md:h-56 object-contain object-center rounded-2xl block bg-[#F9EFEA]"
                      onLoad={() => setLoadedIds((prev) => new Set(prev).add(photo.id))}
                      onError={(e) => {
                        setLoadedIds((prev) => new Set(prev).add(photo.id))
                        const img = e.currentTarget
                        img.style.display = 'none'
                        const parent = img.parentElement
                        if (parent && !parent.querySelector('.photo-fallback')) {
                          const truncated = photo.alt.length > 30 ? photo.alt.slice(0, 30) + '…' : photo.alt
                          parent.insertAdjacentHTML(
                            'beforeend',
                            `<div class="photo-fallback w-full flex flex-col items-center justify-center gap-2 p-4 text-center" style="background: linear-gradient(135deg, #FFD6E0 0%, #E8D5F5 60%, #F5ECD7 100%); min-height: 180px;">
                              <span style="font-size:2.5rem">📸</span>
                              <span style="font-size:0.75rem; color:#B76E79; font-family:'Inter',sans-serif; opacity:0.8; word-break:break-word;">${truncated}</span>
                            </div>`,
                          )
                        }
                      }}
                    />
                  )}

                  {!loadedIds.has(photo.id) && (
                    <div className="absolute inset-0">
                      <PhotoSkeleton message="Hold on — a memory is loading ❤️" />
                    </div>
                  )}
                </div>

                {/* Hover overlay */}
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-2xl flex flex-col justify-end p-3">
                  <p className="text-white text-xs font-medium leading-snug">{photo.alt}</p>
                  {photo.date && (
                    <p className="text-white/60 text-xs">{photo.date}</p>
                  )}
                </div>

                {/* Category badge */}
                <div className="absolute top-2 left-2 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
                  <Badge variant="rose" className="text-[10px] px-2 py-0.5 shadow">
                    {CATEGORIES.find((c) => c.key === photo.category)?.emoji}{' '}
                    {photo.category}
                  </Badge>
                </div>

                {/* Expand affordance — always visible so it's clear the photo opens on click */}
                <div
                  aria-hidden="true"
                  className="absolute bottom-2 right-2 w-8 h-8 flex items-center justify-center rounded-full bg-black/40 text-white opacity-70 group-hover:opacity-100 group-hover:bg-black/60 transition-all duration-200 backdrop-blur-sm"
                >
                  <Expand size={14} />
                </div>
              </motion.figure>
            ))}
          </AnimatePresence>
        </motion.div>
      )}

      {/* ── Navigation CTA ──────────────────────────────────────────────── */}
      <motion.div
        initial={{ opacity: 0, y: 24 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, amount: 0.4 }}
        transition={{ duration: 0.6 }}
        className="flex flex-col items-center gap-4 mt-20"
      >
        <p
          className="text-[#8a4a53] text-lg italic"
          style={{ fontFamily: "'Dancing Script', cursive" }}
        >
          But words can say what photos cannot…
        </p>
        <Button
          variant="primary"
          size="lg"
          onClick={() => navigate('/reasons')}
          ariaLabel="Discover all the reasons I love you"
          className="shadow-[0_4px_24px_rgba(183,110,121,0.3)]"
        >
          100 Reasons I Love You →
        </Button>
      </motion.div>

      {/* ── Lightbox ────────────────────────────────────────────────────── */}
      <AnimatePresence>
        {lightboxIndex !== null && (
          <Lightbox
            photos={filteredPhotos}
            currentIndex={lightboxIndex}
            onClose={closeLightbox}
            onPrev={goPrev}
            onNext={goNext}
          />
        )}
      </AnimatePresence>
    </div>
  )
}
