#!/usr/bin/env node
/*
  import-images.js
  - Copies images and videos from the sibling `images/` folder into `public/images/imported/`
  - Generates `src/data/gallery_imported.ts` with a simple array the app can consume

  Usage: npm run import-images

  Notes:
  - By default expects the source folder at ../images relative to project root (your workspace layout).
  - Adjust SOURCE_DIR constant below if your images live somewhere else.
*/

import fs from 'fs'
import path from 'path'

const SCRIPT_DIR = path.dirname(new URL(import.meta.url).pathname)
const PROJECT_ROOT = path.resolve(SCRIPT_DIR, '..')
// source is ../images (parent of project root) — this matches your provided path
const SOURCE_DIR = path.resolve(PROJECT_ROOT, '..', 'images')
const DEST_DIR = path.resolve(PROJECT_ROOT, 'public', 'images', 'imported')
const OUT_FILE = path.resolve(PROJECT_ROOT, 'src', 'data', 'gallery_imported.ts')

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
}

function slugify(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

function walk(dir, base = '') {
  const items = []
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name)
    const rel = path.join(base, name)
    const stat = fs.statSync(full)
    if (stat.isDirectory()) {
      items.push(...walk(full, rel))
    } else {
      items.push({ full, rel, name })
    }
  }
  return items
}

function detectCategoryFromPath(rel) {
  // attempt to use top-level folder name (e.g. "5th year 2025") as category
  const parts = rel.split(path.sep)
  if (parts.length >= 2) return parts[0]
  return 'all'
}

function niceAlt(name) {
  const noExt = name.replace(/\.[^.]+$/, '')
  const replaced = noExt.replace(/[_-]+/g, ' ')
  const withCaps = replaced.replace(/\b\w/g, (m) => m.toUpperCase())
  return withCaps
}

async function main() {
  console.log('Source dir:', SOURCE_DIR)
  if (!fs.existsSync(SOURCE_DIR)) {
    console.error('Source folder not found. Please place your photos in:', SOURCE_DIR)
    process.exit(1)
  }

  ensureDir(DEST_DIR)
  const files = walk(SOURCE_DIR)
  const allowedExt = ['.jpg', '.jpeg', '.png', '.gif', '.webp', '.mp4', '.mov']
  const entries = []

  for (const f of files) {
    const ext = path.extname(f.name).toLowerCase()
    if (!allowedExt.includes(ext)) continue

    // create destination path preserving folder structure under imported
    const destRel = f.rel
      .split(path.sep)
      .map(slugify)
      .join('/')
    const destFull = path.join(DEST_DIR, destRel)
    ensureDir(path.dirname(destFull))

    // copy file
    fs.copyFileSync(f.full, destFull)

    const webPath = `/images/imported/${destRel}`
    const alt = niceAlt(f.name)
    const category = detectCategoryFromPath(f.rel)

    entries.push({ id: slugify(f.rel), src: webPath, alt, category })
    console.log('Copied', f.rel, '->', webPath)
  }

  // write TS file
  const out = `// Auto-generated by scripts/import-images.js — do not edit by hand
import type { GalleryPhoto } from '../types'

export const importedGallery: GalleryPhoto[] = ${JSON.stringify(entries, null, 2)} as GalleryPhoto[]
`
  ensureDir(path.dirname(OUT_FILE))
  fs.writeFileSync(OUT_FILE, out, 'utf8')

  console.log('\nWrote', OUT_FILE)
  console.log('Import complete. You can now reference importedGallery or copy entries into your gallery data.')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
